[project]
name = "pydantibase"
version = "0.1.0"
description = ""
authors = [
    {name = "mariia",email = "mariia.redchuk@iconservizi.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic (>=2.13.4,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]

[tool.poetry]
packages = [{include = "pydantibase", from = "src"}]

[tool.poetic]
type = "package"
settings = false
progressbar = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
